#################################################
## Weather Forecast from Official MET Malaysia ##
#################################################
## Available range: Today, Yesterday & Tomorrow forecast.
## You are free to do whatever automation from these sensors.
##
## IMPORTANT:
## 1. The sensors are based on command line platform using cURL command.
## 2. Please obtain your METToken and replace it in line 19 from https://api.met.gov.my/
## 3. Change the location code in line 19 (look for LOCATION:288) to your desired location.
## 4. You may refer the location codes table for references.

sensor:
  - platform: command_line
    name: MET Malaysia
    json_attributes:
      - metadata
      - results
    command: 'curl -H "Authorization: METToken 1234567890abcdefghijklmnopqrstuvwxyz1234" "https://api.met.gov.my/v2.1/data?datasetid=FORECAST&datacategoryid=GENERAL&locationid=LOCATION:288&start_date={{ (now().date() + timedelta(days=-1)) }}&end_date={{ (now().date() + timedelta(days=1)) }}"'
    scan_interval: 7200 #2hours interval in second format. Reducing the interval may get you throttled (https://api.met.gov.my/dashboard/docs#throttle). 
    value_template: "{{ value_json.results[1].locationname }}, {{ value_json.results[1].locationrootname }}"
    #icon_template: mdi:weather-cloudy-clock

  - platform: template
    sensors:
        metmalaysia_now:
            friendly_name: "Current Weather"
            icon_template: >-
              {% if as_timestamp(now()) | timestamp_custom('%H') | int < 12 %}{{state_attr("sensor.metmalaysia_fgm", "icon")}}
              {% elif as_timestamp(now()) | timestamp_custom('%H') | int < 18 %}{{state_attr("sensor.metmalaysia_fga", "icon")}}
              {% else %}{{state_attr("sensor.metmalaysia_fgn", "icon")}}
              {% endif %}
            value_template: >-
              {% if as_timestamp(now()) | timestamp_custom('%H') | int < 12 %}{{states.sensor.metmalaysia_fgm.state}}
              {% elif as_timestamp(now()) | timestamp_custom('%H') | int < 18 %}{{states.sensor.metmalaysia_fga.state}}
              {% else %}{{states.sensor.metmalaysia_fgn.state}}
              {% endif %}
        metmalaysia_fgm:
            friendly_name: "Morning Forecast"
            icon_template: >-
              {% if states.sensor.metmalaysia_fgm.state == "Thunderstorms" or states.sensor.metmalaysia_fgm.state == "Rain" %}mdi:weather-pouring
              {% else %}mdi:weather-cloudy
              {% endif %}
            value_template: >-
              {% for x in range(18) -%}
              {% if now().strftime("%Y-%m-%d") == as_datetime(state_attr("sensor.met_malaysia", "results")[x].date).strftime("%Y-%m-%d") and state_attr("sensor.met_malaysia", "results")[x].datatype == 'FGM' %}{{ state_attr("sensor.met_malaysia", "results")[x].value }}
              {% endif -%}
              {% endfor %}
        metmalaysia_fga:
            friendly_name: "Afternoon Forecast"
            icon_template: >-
              {% if states.sensor.metmalaysia_fga.state == "Thunderstorms" or states.sensor.metmalaysia_fga.state == "Rain" %}mdi:weather-pouring
              {% else %}mdi:weather-partly-cloudy
              {% endif %}
            value_template: >-
              {% for x in range(18) -%}
              {% if now().strftime("%Y-%m-%d") == as_datetime(state_attr("sensor.met_malaysia", "results")[x].date).strftime("%Y-%m-%d") and state_attr("sensor.met_malaysia", "results")[x].datatype == 'FGA' %}{{ state_attr("sensor.met_malaysia", "results")[x].value }}
              {% endif -%}
              {% endfor %}
        metmalaysia_fgn:
            friendly_name: "Night Forecast"
            icon_template: >-
              {% if states.sensor.metmalaysia_fgn.state == "Thunderstorms" or states.sensor.metmalaysia_fgn.state == "Rain" %}mdi:weather-pouring
              {% else %}mdi:weather-night-partly-cloudy
              {% endif %}
            value_template: >-
              {% for x in range(18) -%}
              {% if now().strftime("%Y-%m-%d") == as_datetime(state_attr("sensor.met_malaysia", "results")[x].date).strftime("%Y-%m-%d") and state_attr("sensor.met_malaysia", "results")[x].datatype == 'FGN' %}{{ state_attr("sensor.met_malaysia", "results")[x].value }}
              {% endif -%}
              {% endfor %}
        metmalaysia_fmint:
            friendly_name: "Minimum Temperature"
            icon_template: mdi:thermometer
            value_template: >-
              {% for x in range(18) -%}
              {% if now().strftime("%Y-%m-%d") == as_datetime(state_attr("sensor.met_malaysia", "results")[x].date).strftime("%Y-%m-%d") and state_attr("sensor.met_malaysia", "results")[x].datatype == 'FMINT' %}{{ state_attr("sensor.met_malaysia", "results")[x].value }}
              {% endif -%}
              {% endfor %}
            unit_of_measurement: "°C"
        metmalaysia_fmaxt:
            friendly_name: "Maximum Temperature"
            icon_template: mdi:thermometer
            value_template: >-
              {% for x in range(18) -%}
              {% if now().strftime("%Y-%m-%d") == as_datetime(state_attr("sensor.met_malaysia", "results")[x].date).strftime("%Y-%m-%d") and state_attr("sensor.met_malaysia", "results")[x].datatype == 'FMAXT' %}{{ state_attr("sensor.met_malaysia", "results")[x].value }}
              {% endif -%}
              {% endfor %}
            unit_of_measurement: "°C"
        metmalaysia_fsigw:
            friendly_name: "Today Forecast"
            icon_template: mdi:calendar-check
            value_template: >-
              {% for x in range(18) -%}
              {% if now().strftime("%Y-%m-%d") == as_datetime(state_attr("sensor.met_malaysia", "results")[x].date).strftime("%Y-%m-%d") and state_attr("sensor.met_malaysia", "results")[x].datatype == 'FSIGW' %}{{ state_attr("sensor.met_malaysia", "results")[x].value }}
              {% endif -%}
              {% endfor %}
            attribute_templates: 
              when: >-
                {% for x in range(18) -%}
                {% if now().strftime("%Y-%m-%d") == as_datetime(state_attr("sensor.met_malaysia", "results")[x].date).strftime("%Y-%m-%d") and state_attr("sensor.met_malaysia", "results")[x].datatype == 'FSIGW' %}{{ state_attr("sensor.met_malaysia", "results")[x].attributes.when }}
                {% endif -%}
                {% endfor %}
        metmalaysia_fsigw_tomorrow:
            friendly_name: "Tomorrow Forecast"
            icon_template: mdi:calendar-month
            value_template: >-
              {% for x in range(18) -%}
              {% if (now() + timedelta(days=1)).strftime("%Y-%m-%d") == as_datetime(state_attr("sensor.met_malaysia", "results")[x].date).strftime("%Y-%m-%d") and state_attr("sensor.met_malaysia", "results")[x].datatype == 'FSIGW' %}{{ state_attr("sensor.met_malaysia", "results")[x].value }}
              {% endif -%}
              {% endfor %}
            attribute_templates: 
              when: >-
                {% for x in range(18) -%}
                {% if (now() + timedelta(days=1)).strftime("%Y-%m-%d") == as_datetime(state_attr("sensor.met_malaysia", "results")[x].date).strftime("%Y-%m-%d") and state_attr("sensor.met_malaysia", "results")[x].datatype == 'FSIGW' %}{{ state_attr("sensor.met_malaysia", "results")[x].attributes.when }}
                {% endif -%}
                {% endfor %}
        metmalaysia_fsigw_yesterday:
            friendly_name: "Yesterday Forecast"
            icon_template: mdi:calendar-month-outline
            value_template: >-
              {% for x in range(18) -%}
              {% if (now() + timedelta(days=-1)).strftime("%Y-%m-%d") == as_datetime(state_attr("sensor.met_malaysia", "results")[x].date).strftime("%Y-%m-%d") and state_attr("sensor.met_malaysia", "results")[x].datatype == 'FSIGW' %}{{ state_attr("sensor.met_malaysia", "results")[x].value }}
              {% endif -%}
              {% endfor %}
            attribute_templates: 
              when: >-
                {% for x in range(18) -%}
                {% if (now() + timedelta(days=-1)).strftime("%Y-%m-%d") == as_datetime(state_attr("sensor.met_malaysia", "results")[x].date).strftime("%Y-%m-%d") and state_attr("sensor.met_malaysia", "results")[x].datatype == 'FSIGW' %}{{ state_attr("sensor.met_malaysia", "results")[x].attributes.when }}
                {% endif -%}
                {% endfor %}
